version: '3.7'

services:

  trac:
    image: stephenhsu/trac

    ports:
      - 8123:8123

    volumes:
      # Need to spell this out so that docker-compose doesn't complain about nested read-only mounts
      - ./meta-repository/trac.wordpress.org/conf/common-extended.ini:/var/local/trac/conf/common-extended.ini:ro
      - ./meta-repository/trac.wordpress.org/conf/common.ini:/var/local/trac/conf/common.ini:ro
      - ./meta-repository/trac.wordpress.org/conf/focuses.ini:/var/local/trac/conf/focuses.ini:ro
      - ./meta-repository/trac.wordpress.org/conf/intertrac.ini:/var/local/trac/conf/intertrac.ini:ro
      - ./meta-repository/trac.wordpress.org/conf/notifications.ini:/var/local/trac/conf/notifications.ini:ro
      - ./meta-repository/trac.wordpress.org/conf/workflow-core-test.ini:/var/local/trac/conf/workflow-core-test.ini:ro
      - ./meta-repository/trac.wordpress.org/conf/workflow-core.ini:/var/local/trac/conf/workflow-core.ini:ro
      - ./meta-repository/trac.wordpress.org/conf/workflow-themes.ini:/var/local/trac/conf/workflow-themes.ini:ro

      - ./trac.ini:/var/local/trac/conf/trac.ini:ro

      - ./meta-repository/trac.wordpress.org/templates:/var/local/trac/templates:ro

      - ./db:/var/local/trac/db
